Sprint_2_qa
asyatestp/qa_python pull request #1
Opened 2023-07-02 17:23 UTC by asyatestp

2023-07-03 18:45 UTC, kadirovgm requested changes

2023-07-03 18:45 UTC, kadirovgm commented on .idea/inspectionProfiles/Project_Default.xml
нужно исправить: этот файл не относится к проекту, не стоит его мержить в общий репозиторий. Лучше его удалить либо добавить в файл гитигнор

2023-07-03 18:45 UTC, kadirovgm commented on .idea/inspectionProfiles/profiles_settings.xml
нужно исправить: этот файл не относится к проекту, не стоит его мержить в общий репозиторий. Лучше его удалить либо добавить в файл гитигнор

2023-07-03 18:45 UTC, kadirovgm commented on .idea/misc.xml
нужно исправить: этот файл не относится к проекту, не стоит его мержить в общий репозиторий. Лучше его удалить либо добавить в файл гитигнор

2023-07-03 18:45 UTC, kadirovgm commented on .idea/modules.xml
нужно исправить: этот файл не относится к проекту, не стоит его мержить в общий репозиторий. Лучше его удалить либо добавить в файл гитигнор

2023-07-03 18:45 UTC, kadirovgm commented on .idea/qa_python.iml
нужно исправить: этот файл не относится к проекту, не стоит его мержить в общий репозиторий. Лучше его удалить либо добавить в файл гитигнор

2023-07-03 18:45 UTC, kadirovgm commented on .idea/vcs.xml
нужно исправить: этот файл не относится к проекту, не стоит его мержить в общий репозиторий. Лучше его удалить либо добавить в файл гитигнор

2023-07-03 18:45 UTC, kadirovgm commented on README.md
> +# qa_python
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов

2023-07-03 18:45 UTC, kadirovgm commented on tests.py
> +    def test_set_book_rating_check_book_rating_5(self):
Можно лучше: PEP8 - между методами стоит оставлять пустую строку

2023-07-03 18:45 UTC, kadirovgm commented on tests.py
> +
можно лучше: перед началом методов стоит оставлять краткий комментарий, что тест проверяет, лучше воспользоваться методом комментрирования "докстринг"

2023-07-03 18:45 UTC, kadirovgm commented on tests.py
> +    def test_set_book_rating_check_book_rating_below_the_border(self):
нужно исправить: сама проверка верная, но по заданию для проверки граничных невалидных значений стоит воспользоваться параметризацией. Здесь у тебя может быть несколько одинаковых тестов, отличающихся только входными данными, в таком случае обязательно пользоваться параметризацией, чтобы не допускать повторений в коде

2023-07-03 18:45 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books()[0] == 'Гордость и предубеждение и зомби'
можно лучше: здесь также можно воспользоваться конструкцией in/not in, но твой вариант также неплох

хотя этот тест частично повторяет test_add_book_in_favorites, но считаю норм и это проверить тоже :)

2023-07-04 21:03 UTC, kadirovgm requested changes

2023-07-04 21:03 UTC, kadirovgm commented on tests.py
> +    def test_set_book_rating_check_book_rating_below_the_border(self, rating):
нужно исправить: кажется в таком случае стоит переименовать тест

2023-07-04 21:03 UTC, kadirovgm commented on tests.py
>      def test_set_book_rating_check_book_rating_above_the_border(self):
нужно исправить:  для чего этот тест теперь, если ты в тесте выше этот кейс уже учла?

2023-07-04 21:03 UTC, kadirovgm commented on .pytest_cache/.gitignore
нужно исправить: перемести папку .pytest_cache все в гитигнор

2023-07-05 08:52 UTC, asyatestp commented on .pytest_cache/.gitignore
Добрый день
Добавила ее, но не понимаю почему она видна

2023-07-05 21:53 UTC, kadirovgm approved these changes

2023-07-08 14:11 UTC, merged